package com.jack.graduation.bean;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;

@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Album {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.id
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.artist_id
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String artistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.album_title
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String albumTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.genre
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String genre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.year_of_pub
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String yearOfPub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.num_of_tracks
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String numOfTracks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.num_of_sales
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String numOfSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.rolling_stone_critic
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String rollingStoneCritic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.mtv_critic
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String mtvCritic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.music_maniac_critic
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String musicManiacCritic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column albums_info.record_time
     *
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    private String recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.id
     *
     * @return the value of albums_info.id
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.id
     *
     * @param id the value for albums_info.id
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.artist_id
     *
     * @return the value of albums_info.artist_id
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getArtistId() {
        return artistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.artist_id
     *
     * @param artistId the value for albums_info.artist_id
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setArtistId(String artistId) {
        this.artistId = artistId == null ? null : artistId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.album_title
     *
     * @return the value of albums_info.album_title
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getAlbumTitle() {
        return albumTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.album_title
     *
     * @param albumTitle the value for albums_info.album_title
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setAlbumTitle(String albumTitle) {
        this.albumTitle = albumTitle == null ? null : albumTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.genre
     *
     * @return the value of albums_info.genre
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getGenre() {
        return genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.genre
     *
     * @param genre the value for albums_info.genre
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setGenre(String genre) {
        this.genre = genre == null ? null : genre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.year_of_pub
     *
     * @return the value of albums_info.year_of_pub
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getYearOfPub() {
        return yearOfPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.year_of_pub
     *
     * @param yearOfPub the value for albums_info.year_of_pub
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setYearOfPub(String yearOfPub) {
        this.yearOfPub = yearOfPub == null ? null : yearOfPub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.num_of_tracks
     *
     * @return the value of albums_info.num_of_tracks
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getNumOfTracks() {
        return numOfTracks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.num_of_tracks
     *
     * @param numOfTracks the value for albums_info.num_of_tracks
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setNumOfTracks(String numOfTracks) {
        this.numOfTracks = numOfTracks == null ? null : numOfTracks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.num_of_sales
     *
     * @return the value of albums_info.num_of_sales
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getNumOfSales() {
        return numOfSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.num_of_sales
     *
     * @param numOfSales the value for albums_info.num_of_sales
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setNumOfSales(String numOfSales) {
        this.numOfSales = numOfSales == null ? null : numOfSales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.rolling_stone_critic
     *
     * @return the value of albums_info.rolling_stone_critic
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getRollingStoneCritic() {
        return rollingStoneCritic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.rolling_stone_critic
     *
     * @param rollingStoneCritic the value for albums_info.rolling_stone_critic
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setRollingStoneCritic(String rollingStoneCritic) {
        this.rollingStoneCritic = rollingStoneCritic == null ? null : rollingStoneCritic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.mtv_critic
     *
     * @return the value of albums_info.mtv_critic
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getMtvCritic() {
        return mtvCritic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.mtv_critic
     *
     * @param mtvCritic the value for albums_info.mtv_critic
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setMtvCritic(String mtvCritic) {
        this.mtvCritic = mtvCritic == null ? null : mtvCritic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.music_maniac_critic
     *
     * @return the value of albums_info.music_maniac_critic
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getMusicManiacCritic() {
        return musicManiacCritic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.music_maniac_critic
     *
     * @param musicManiacCritic the value for albums_info.music_maniac_critic
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setMusicManiacCritic(String musicManiacCritic) {
        this.musicManiacCritic = musicManiacCritic == null ? null : musicManiacCritic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column albums_info.record_time
     *
     * @return the value of albums_info.record_time
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public String getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column albums_info.record_time
     *
     * @param recordTime the value for albums_info.record_time
     * @mbggenerated Sun Jan 01 19:02:42 CST 2023
     */
    public void setRecordTime(String recordTime) {
        this.recordTime = recordTime == null ? null : recordTime.trim();
    }
}