package com.jack.graduation.bean;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.data.relational.core.mapping.Table;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;


@Table("file_info")
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class FileInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.id
     *
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_name
     *
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    private String fileName;
    private String fileMd5;
    private String uuid;

    public String getfileMd5() {
        return fileMd5;
    }

    public void setfileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_type
     *
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_size
     *
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.url
     *
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.is_etl
     *
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    private Integer isEtl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.upload_time
     *
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.etl_time
     *
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
//    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date etlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.update_time
     *
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.id
     *
     * @return the value of file_info.id
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.id
     *
     * @param id the value for file_info.id
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_name
     *
     * @return the value of file_info.file_name
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_name
     *
     * @param fileName the value for file_info.file_name
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_type
     *
     * @return the value of file_info.file_type
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_type
     *
     * @param fileType the value for file_info.file_type
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_size
     *
     * @return the value of file_info.file_size
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_size
     *
     * @param fileSize the value for file_info.file_size
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.url
     *
     * @return the value of file_info.url
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.url
     *
     * @param url the value for file_info.url
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.is_etl
     *
     * @return the value of file_info.is_etl
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public Integer getIsEtl() {
        return isEtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.is_etl
     *
     * @param isEtl the value for file_info.is_etl
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public void setIsEtl(Integer isEtl) {
        this.isEtl = isEtl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.upload_time
     *
     * @return the value of file_info.upload_time
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.upload_time
     *
     * @param uploadTime the value for file_info.upload_time
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.etl_time
     *
     * @return the value of file_info.etl_time
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public Date getEtlTime() {
        return etlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.etl_time
     *
     * @param etlTime the value for file_info.etl_time
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public void setEtlTime(Date etlTime) {
        this.etlTime = etlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.update_time
     *
     * @return the value of file_info.update_time
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.update_time
     *
     * @param updateTime the value for file_info.update_time
     * @mbggenerated Thu Jan 05 17:55:10 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}